---
- name: Backup show run (enable mode commands)
  hosts: gns3-core #:gns3-access
  gather_facts: false
  connection: local

  tasks:
    - name: run enable commands on remote nodes
      ios_command:
        authorize: yes
        commands:
          - show running-config
      # raw: "show version"
      register: print_output

    - debug:
        var: print_output.stdout_lines

    - name: save to output file
      copy:
        content: "{{ print_output.stdout[0]}}"
        dest: ./output/{{inventory_hostname}}.txt


#         ansible-playbook getrun.yml -u bryan -k
# SSH password: 
# [DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to 
# allow bad characters in group names by default, this will change, but still be 
# user configurable on deprecation. This feature will be removed in version 2.10.
#  Deprecation warnings can be disabled by setting deprecation_warnings=False in 
# ansible.cfg.
# [WARNING]: Invalid characters were found in group names but not replaced, use
# -vvvv to see details

# PLAY [Backup show run (enable mode commands)] **********************************

# TASK [run enable commands on remote nodes] *************************************
#     ok: [csw2]
# ok: [csw1]

# TASK [debug] *******************************************************************
# ok: [csw1] => {
#     "print_output.stdout_lines": [
#         [
#             "Building configuration...",
#             "",
#             "Current configuration : 3628 bytes",
#             "!",
#             "! Last configuration change at 16:38:44 UTC Sun Apr 5 2026",
#             "!",
#             "version 15.2",
#             "service timestamps debug datetime msec",
#             "service timestamps log datetime msec",
#             "no service password-encryption",
#             "service compress-config",
#             "!",
#             "hostname CSW1",
#             "!",
#             "boot-start-marker",
#             "boot-end-marker",
#             "!",
#             "!",
#             "!",
#             "username bryan privilege 15 secret 5 $1$Jjcc$gSt2YAQf48IoDg2TjpKv41",
#             "no aaa new-model",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "ip domain-name bryansit.com",
#             "ip cef",
#             "no ipv6 cef",
#             "!",
#             "!",
#             "!",
#             "spanning-tree mode pvst",
#             "spanning-tree extend system-id",
#             "!",
#             "!",
#             "! ",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "interface Port-channel1",
#             "!",
#             "interface GigabitEthernet0/0",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet0/1",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet0/2",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet0/3",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet1/0",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet1/1",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet1/2",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet1/3",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet2/0",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet2/1",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet2/2",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet2/3",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet3/0",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet3/1",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet3/2",
#             " negotiation auto",
#             " channel-group 1 mode active",
#             "!",
#             "interface GigabitEthernet3/3",
#             " negotiation auto",
#             " channel-group 1 mode active",
#             "!",
#             "interface Vlan1",
#             " ip address 192.168.42.31 255.255.255.0",
#             "!",
#             "ip default-gateway 192.168.42.1",
#             "ip forward-protocol nd",
#             "!",
#             "ip http server",
#             "ip http secure-server",
#             "!",
#             "ip route 0.0.0.0 0.0.0.0 192.168.42.1",
#             "ip ssh server algorithm encryption aes128-ctr aes192-ctr aes256-ctr",
#             "ip ssh client algorithm encryption aes128-ctr aes192-ctr aes256-ctr",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "snmp-server community zabbix RO",
#             "snmp-server location Lab",
#             "snmp-server contact bryan",
#             "!",
#             "control-plane",
#             "!",
#             "banner exec ^C",
#             "IOSv - Cisco Systems Confidential -",
#             "",
#             "Supplemental End User License Restrictions",
#             "",
#             "This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.",
#             "",
#             "By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.",
#             "^C",
#             "banner incoming ^C",
#             "IOSv - Cisco Systems Confidential -",
#             "",
#             "Supplemental End User License Restrictions",
#             "",
#             "This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.",
#             "",
#             "By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.",
#             "^C",
#             "banner login ^C",
#             "IOSv - Cisco Systems Confidential -",
#             "",
#             "Supplemental End User License Restrictions",
#             "",
#             "This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.",
#             "",
#             "By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.",
#             "^C",
#             "!",
#             "line con 0",
#             "line aux 0",
#             "line vty 0 4",
#             " login local",
#             " transport input all",
#             "!",
#             "!",
#             "end"
#         ]
#     ]
# }
# ok: [csw2] => {
#     "print_output.stdout_lines": [
#         [
#             "Building configuration...",
#             "",
#             "Current configuration : 3628 bytes",
#             "!",
#             "! Last configuration change at 16:38:51 UTC Sun Apr 5 2026",
#             "!",
#             "version 15.2",
#             "service timestamps debug datetime msec",
#             "service timestamps log datetime msec",
#             "no service password-encryption",
#             "service compress-config",
#             "!",
#             "hostname CSW2",
#             "!",
#             "boot-start-marker",
#             "boot-end-marker",
#             "!",
#             "!",
#             "!",
#             "username bryan privilege 15 secret 5 $1$uGcg$3rSasVXm3xp3HW3Lw35cT0",
#             "no aaa new-model",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "ip domain-name bryansit.com",
#             "ip cef",
#             "no ipv6 cef",
#             "!",
#             "!",
#             "!",
#             "spanning-tree mode pvst",
#             "spanning-tree extend system-id",
#             "!",
#             "!",
#             "! ",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "interface Port-channel1",
#             "!",
#             "interface GigabitEthernet0/0",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet0/1",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet0/2",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet0/3",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet1/0",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet1/1",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet1/2",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet1/3",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet2/0",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet2/1",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet2/2",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet2/3",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet3/0",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet3/1",
#             " negotiation auto",
#             "!",
#             "interface GigabitEthernet3/2",
#             " negotiation auto",
#             " channel-group 1 mode active",
#             "!",
#             "interface GigabitEthernet3/3",
#             " negotiation auto",
#             " channel-group 1 mode active",
#             "!",
#             "interface Vlan1",
#             " ip address 192.168.42.32 255.255.255.0",
#             "!",
#             "ip default-gateway 192.168.42.1",
#             "ip forward-protocol nd",
#             "!",
#             "ip http server",
#             "ip http secure-server",
#             "!",
#             "ip route 0.0.0.0 0.0.0.0 192.168.42.1",
#             "ip ssh server algorithm encryption aes128-ctr aes192-ctr aes256-ctr",
#             "ip ssh client algorithm encryption aes128-ctr aes192-ctr aes256-ctr",
#             "!",
#             "!",
#             "!",
#             "!",
#             "!",
#             "snmp-server community zabbix RO",
#             "snmp-server location Lab",
#             "snmp-server contact bryan",
#             "!",
#             "control-plane",
#             "!",
#             "banner exec ^C",
#             "IOSv - Cisco Systems Confidential -",
#             "",
#             "Supplemental End User License Restrictions",
#             "",
#             "This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.",
#             "",
#             "By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.",
#             "^C",
#             "banner incoming ^C",
#             "IOSv - Cisco Systems Confidential -",
#             "",
#             "Supplemental End User License Restrictions",
#             "",
#             "This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.",
#             "",
#             "By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.",
#             "^C",
#             "banner login ^C",
#             "IOSv - Cisco Systems Confidential -",
#             "",
#             "Supplemental End User License Restrictions",
#             "",
#             "This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.",
#             "",
#             "By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.",
#             "^C",
#             "!",
#             "line con 0",
#             "line aux 0",
#             "line vty 0 4",
#             " login local",
#             " transport input all",
#             "!",
#             "!",
#             "end"
#         ]
#     ]
# }

# TASK [save to output file] *****************************************************
# changed: [csw1]
# changed: [csw2]

# PLAY RECAP *********************************************************************
# csw1                       : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
# csw2                       : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   