---
# Router configs
- name: enable ospf
  hosts: gns3_router
  gather_facts: false
  connection: network_cli        # modern connection method
  tasks:
    - name: enable ospf
      ios_config:
        authorize: yes
        parents: router ospf 1
        lines:
          - network 0.0.0.0 255.255.255.255 area 0
      register: print_output
    - debug:
        var: print_output.updates

# Switch configs
- name: Switch specific config
  hosts: gns3_core
  gather_facts: false
  connection: network_cli        # modern connection method
  tasks:
    - name: Create VLANS
      ios_config:
        authorize: yes
        lines:
          - vlan 20
          - vlan 30
          - vlan 40
          - vlan 50
      register: print_output
    - debug:
        var: print_output.updates